version: "3.6"
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  node-app:
    build: .
    depends_on:
      - mongodb
      - redis_db
      - nginx

  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=adesh
      - MONGO_INITDB_ROOT_PASSWORD=mypass
    volumes:
      - mongo-db:/data/db

  redis_db:
    image: redis
    ports:
      - 127.0.0.1:6379:6379

volumes:
  mongo-db:
