version: "3.6"
services:
  nginx:
    ports:
      - 3000:80

  node-app:
    build:
      context: .
      args:
        - NODE_ENV=dev
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=dev
    command: npm start
