version: "3.6"
services:
  node-app:
    build: .
    ports:
      - "3000:5000"
    environment:
      - PORT=5000
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=adesh
      - MONGO_INITDB_ROOT_PASSWORD=mypass
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
