version: "3.6"
services:
  nginx:
    ports:
      - 80:80

  node-app:
    deploy:
      replicas: 4
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 10s
    build:
      context: .
      args:
        - NODE_ENV=prod
    environment:
      - NODE_ENV=prod
    command: node ./dist/index.js
