version: "3.6"
services:
  nginx:
    ports:
      - 80:80

  node-app:
    build:
      context: .
      args:
        - NODE_ENV=prod
    environment:
      - NODE_ENV=prod
    command: node ./dist/index.js
